#!/bin/bash
# chkconfig: 2345 90 10
# description: Shadowsocks Golang

### BEGIN INIT INFO
# Provides:          Shadowsocks Golang
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lightweight SOCKS5 proxy tool Shadowsocks
# Description:       Start or stop the Shadowsocks-go
### END INIT INFO

NAME="Shadowsocks"
NAME_BIN="./shadowsocks-go "
FOLDER="/usr/local/shadowsocks-go"
CONF="/usr/local/shadowsocks-go/shadowsocks-go.conf"
LOG="/usr/local/shadowsocks-go/shadowsocks-go.log"

Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
Info="${Green_font_prefix}[정보]${Font_color_suffix}"
Error="${Red_font_prefix}[오류]${Font_color_suffix}"
RETVAL=0

check_running(){
	PID=$(ps -ef |grep "${NAME_BIN}" |grep -v "grep" |grep -v "init.d" |grep -v "service" |awk '{print $2}')
	if [[ ! -z ${PID} ]]; then
		return 0
	else
		return 1
	fi
}
read_config(){
	[[ ! -e ${CONF} ]] && echo -e "${Error} $NAME 설정 파일없음 !" && exit 1
	port=$(cat ${CONF}|grep 'PORT = '|awk -F 'PORT = ' '{print $NF}')
	password=$(cat ${CONF}|grep 'PASSWORD = '|awk -F 'PASSWORD = ' '{print $NF}')
	cipher=$(cat ${CONF}|grep 'CIPHER = '|awk -F 'CIPHER = ' '{print $NF}')
	verbose=$(cat ${CONF}|grep 'VERBOSE = '|awk -F 'VERBOSE = ' '{print $NF}')
	if [[ "${verbose}" == "YES" ]]; then
		verbose="-verbose"
	else
		verbose=""
	fi
}
do_start(){
	check_running
	if [[ $? -eq 0 ]]; then
		echo -e "${Info} $NAME (PID ${PID}) 실행중..." && exit 0
	else
		read_config
		cd ${FOLDER}
		echo -e "${Info} $NAME 시작중..."
		ulimit -n 51200
		nohup ./shadowsocks-go -s ":${port}" -cipher "${cipher}" -password "${password}" "${verbose}" >> "${LOG}" 2>&1 &
		sleep 2s
		check_running
		if [[ $? -eq 0 ]]; then
			echo -e "${Info} $NAME 실행 성공 !"
		else
			echo -e "${Error} $NAME 실행 실패 ! 로그파일을 확인하여 문제점을 확인하세요."
		fi
	fi
}
do_stop(){
	check_running
	if [[ $? -eq 0 ]]; then
		kill -9 ${PID}
		RETVAL=$?
		if [[ $RETVAL -eq 0 ]]; then
			echo -e "${Info} $NAME 중지 성공 !"
		else
			echo -e "${Error} $NAME 중지 실패 !"
		fi
	else
		echo -e "${Info} $NAME 미실행"
		RETVAL=1
	fi
}
do_status(){
	check_running
	if [[ $? -eq 0 ]]; then
		echo -e "${Info} $NAME (PID ${PID}) 실행중..."
	else
		echo -e "${Info} $NAME 미실행 !"
		RETVAL=1
	fi
}
do_restart(){
	do_stop
	do_start
}
case "$1" in
	start|stop|restart|status)
	do_$1
	;;
	*)
	echo -e "사용방법: $0 { start | stop | restart | status }"
	RETVAL=1
	;;
esac
exit $RETVAL
